name: ipfs_node_flutter
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  ipfs_node_flutter_platform_interface:
    path: ../ipfs_node_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: ipfs_node_flutter_native
      ios:
        default_package: ipfs_node_flutter_native
      macos:
        default_package: ipfs_node_flutter_native
      windows:
        default_package: ipfs_node_flutter_native
      linux:
        default_package: ipfs_node_flutter_native
      web:
        default_package: ipfs_node_flutter_web
