name: ipfs_node_flutter_native
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  ipfs_node_flutter:
    path: ../ipfs_node_flutter
  ipfs_node_flutter_platform_interface:
    path: ../ipfs_node_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: ipfs_node_flutter
    platforms:
      android:
        dartPluginClass: IpfsNodeFlutterNative
      ios:
        dartPluginClass: IpfsNodeFlutterNative
      macos:
        dartPluginClass: IpfsNodeFlutterNative
      windows:
        dartPluginClass: IpfsNodeFlutterNative
        ffiPlugin: true
      linux:
        dartPluginClass: IpfsNodeFlutterNative
